Repository boostcampwm-2024/refactor-web05-Denamu, pull requests merged in 2025-01, with the labels that each got.

#2 ♻️ refactor: FeedCrawler OOP 적용
  feed-crawler/package-lock.json
  feed-crawler/package.json
  feed-crawler/src/common/mysql-access.ts
  feed-crawler/src/container.ts
  feed-crawler/src/feed-crawler.ts
  feed-crawler/src/main.ts
  feed-crawler/src/repository/feed.repository.ts
  feed-crawler/src/repository/rss.repository.ts
  feed-crawler/src/types/database-connection.ts
  feed-crawler/src/types/dependency-symbols.ts
Labels: 🔨 Refactor

#3 ♻️ refactor: chatgateway의 관심사 분리, 채팅 비즈니스 로직을 chatservice로 구현
  server/src/chat/chat.gateway.ts
  server/src/chat/chat.module.ts
  server/src/chat/chat.service.ts
Labels: 🔨 Refactor

#6 ♻️ refactor: cron을 사용하는 scheduler 메서드를 추출, FeedScheduler로 리팩토링
  server/src/app.module.ts
  server/src/chat/chat.gateway.ts
  server/src/chat/chat.module.ts
  server/src/chat/chat.type.ts
  server/src/chat/module/chat.module.ts
  server/src/chat/scheduler/chat.scheduler.ts
  server/src/chat/service/chat.service.ts
  server/src/feed/module/feed.module.ts
  server/src/feed/scheduler/feed.scheduler.ts
  server/src/feed/service/feed.service.ts
Labels: 🔨 Refactor

#5 ♻️ refactor: 데이터 전처리 Repository 계층으로 위임
  server/src/rss/service/feed-crawler.service.ts
  server/src/rss/service/rss.service.ts
Labels: 🔨 Refactor

#10 ♻️ refactor: Redis 동작 메서드 캡슐화
  feed-crawler/src/common/redis-access.ts
  feed-crawler/src/container.ts
  feed-crawler/src/repository/feed.repository.ts
  feed-crawler/src/types/dependency-symbols.ts
  server/src/admin/service/admin.service.ts
  server/src/chat/service/chat.service.ts
  server/src/common/guard/auth.guard.ts
  server/src/common/redis/redis.service.ts
  server/src/feed/scheduler/feed.scheduler.ts
  server/src/feed/service/feed.service.ts
  server/src/statistic/service/statistic.service.ts
  server/test/admin/e2e/logout.e2e-spec.ts
  server/test/feed/e2e/feedId.e2e-spec.ts
  server/test/feed/e2e/recent.e2e-spec.ts
  server/test/feed/e2e/trend.e2e-spec.ts
  server/test/rss/e2e/accept.e2e-spec.ts
  server/test/rss/e2e/history/accept.e2e-spec.ts
  server/test/rss/e2e/history/reject.e2e-spec.ts
  server/test/rss/e2e/reject.e2e-spec.ts
  server/test/statistic/e2e/today.e2e-spec.ts
Labels: 🔨 Refactor

#9 ♻️ refactor: Response DTO 적용, request/response 분리
  server/src/admin/controller/admin.controller.ts
  server/src/admin/dto/request/login-admin.dto.ts
  server/src/admin/dto/request/register-admin.dto.ts
  server/src/admin/repository/admin.repository.ts
  server/src/admin/service/admin.service.ts
  server/src/feed/api-docs/searchFeedList.api-docs.ts
  server/src/feed/controller/feed.controller.ts
  server/src/feed/dto/request/feed-pagination.dto.ts
  server/src/feed/dto/request/search-feed.dto.ts
  server/src/feed/dto/response/feed-pagination.dto.ts
  server/src/feed/dto/response/recent.dto.ts
  server/src/feed/dto/response/search-feed.dto.ts
  server/src/feed/repository/feed.repository.ts
  server/src/feed/service/feed.service.ts
  server/src/rss/controller/rss.controller.ts
  server/src/rss/dto/request/rss-management.dto.ts
  server/src/rss/dto/request/rss-register.dto.ts
  server/src/rss/dto/request/rss-reject.dto.ts
  server/src/rss/dto/response/rss-accept-history.dto.ts
  server/src/rss/dto/response/rss-all.dto.ts
  server/src/rss/dto/response/rss-reject-history.dto.ts
  server/src/rss/repository/rss.repository.ts
  server/src/rss/service/rss.service.ts
  server/src/statistic/controller/statistic.controller.ts
  server/src/statistic/dto/platform-response.dto.ts
  server/src/statistic/dto/request/statistic-query.dto.ts
  server/src/statistic/dto/response/all-view-count.dto.ts
  server/src/statistic/dto/response/platform.dto.ts
  server/src/statistic/dto/response/today.dto.ts
  server/src/statistic/service/statistic.service.ts
  server/test/admin/dto/login-admin.dto.spec.ts
  server/test/admin/dto/register-admin.dto.spec.ts
  server/test/admin/e2e/login.e2e-spec.ts
  server/test/admin/e2e/register.e2e-spec.ts
  server/test/admin/e2e/sessionId.e2e-spec.ts
  server/test/feed/dto/feed-pagination.dto.spec.ts
  server/test/feed/dto/search-feed.dto.spec.ts
  server/test/rss/dto/rss-management.dto.spec.ts
  server/test/rss/dto/rss-register.dto.spec.ts
  server/test/rss/e2e/reject.e2e-spec.ts
  server/test/rss/e2e/rss.e2e-spec.ts
  server/test/statistic/dto/statistic-query.dto.spec.ts
Labels: 🔨 Refactor

#7 ♻️ refactor: 소소한 코드정리
  client/.gitignore
  client/src/components/chart/BarChartItem.tsx
  client/src/components/chat/ChatItem.tsx
  client/src/hooks/queries/useSearch.ts
Labels: 🔨 Refactor

#8 ♻️ refactor: admin 컴포넌트 코드 리팩토링
  client/src/components/admin/layout/AdminHeader.tsx
  client/src/components/admin/layout/AdminMember.tsx
  client/src/components/admin/layout/AdminNavigationMenu.tsx
  client/src/components/admin/layout/AdminTabs.tsx
  client/src/components/admin/login/AdminLoginModal.tsx
  client/src/components/admin/rss/RejectModal.tsx
  client/src/components/admin/rss/RssRequestCard.tsx
  client/src/components/admin/rss/RssResponseCard.tsx
  client/src/components/admin/rss/RssSearchBar.tsx
  client/src/components/admin/tabs/AcceptedTab.tsx
  client/src/components/admin/tabs/PendingTab.tsx
  client/src/components/admin/tabs/RejectedTab.tsx
Labels: 🔨 Refactor

#4 ♻️ refactor: API 엔드포인트 상수처리
  client/src/api/instance.ts
  client/src/api/services/admin/auth.ts
  client/src/api/services/admin/register.ts
  client/src/api/services/admin/rss.ts
  client/src/api/services/chart/chart.ts
  client/src/api/services/posts.ts
  client/src/api/services/rss.ts
  client/src/api/services/search.ts
  client/src/api/services/view.ts
  client/src/constants/endpoints.ts
  client/src/store/useChatStore.ts
Labels: 🔨 Refactor

#11 🧼 clean: 코드 일관성 향상
  feed-crawler/src/repository/feed.repository.ts
  server/src/admin/controller/admin.controller.ts
  server/src/admin/dto/request/login-admin.dto.ts
  server/src/admin/dto/request/register-admin.dto.ts
  server/src/feed/api-docs/searchFeedList.api-docs.ts
  server/src/feed/api-docs/updateFeedViewCount.api-docs.ts
  server/src/feed/controller/feed.controller.ts
  server/src/feed/dto/request/feed-update.dto.ts
  server/src/feed/dto/response/feed-pagination.dto.ts
  server/src/feed/service/feed.service.ts
  server/src/main.ts
  server/src/rss/controller/rss.controller.ts
  server/src/rss/dto/request/rss-register.dto.ts
  server/src/rss/service/rss.service.ts
  server/src/statistic/controller/statistic.controller.ts
  server/src/statistic/service/statistic.service.ts
  server/test/feed/e2e/trend.e2e-spec.ts
  server/test/jest.setup.ts
  server/test/rss/e2e/history/accept.e2e-spec.ts
  server/test/rss/e2e/history/reject.e2e-spec.ts
  server/test/statistic/e2e/all.e2e-spec.ts
  server/test/statistic/e2e/today.e2e-spec.ts
Labels: 🧹 Cleanup

#14 ♻️ refactor: admin 도메인 repository 함수 재사용성 향상, 테스트 코드 일관성, 최적화
  server/package-lock.json
  server/package.json
  server/src/admin/controller/admin.controller.ts
  server/src/admin/dto/request/login-admin.dto.ts
  server/src/admin/dto/request/register-admin.dto.ts
  server/src/admin/repository/admin.repository.ts
  server/src/admin/service/admin.service.ts
  server/src/feed/controller/feed.controller.ts
  server/src/feed/service/feed.service.ts
  server/src/rss/controller/rss.controller.ts
  server/src/rss/service/rss.service.ts
  server/src/statistic/controller/statistic.controller.ts
  server/src/statistic/service/statistic.service.ts
  server/test/admin/dto/login-admin.dto.spec.ts
  server/test/admin/dto/register-admin.dto.spec.ts
  server/test/admin/e2e/login.e2e-spec.ts
  server/test/admin/e2e/register.e2e-spec.ts
  server/test/admin/e2e/sessionId.e2e-spec.ts
  server/test/fixture/admin.fixture.ts
Labels: 🔨 Refactor, ✅ Test

#15 ♻️ refactor: feed 도메인 repository 함수 재사용성 향상, 테스트 코드 일관성, 최적화
  server/src/feed/dto/request/feed-pagination.dto.ts
  server/src/feed/dto/request/feed-update.dto.ts
  server/src/feed/repository/feed.repository.ts
  server/src/feed/service/feed.service.ts
  server/test/feed/dto/feed-pagination.dto.spec.ts
  server/test/feed/dto/feed-update.dto.spec.ts
  server/test/feed/e2e/feed.e2e-spec.ts
  server/test/feed/e2e/feedId.e2e-spec.ts
  server/test/feed/e2e/trend.e2e-spec.ts
Labels: 🔨 Refactor, ✅ Test

#17 ♻️ refactor: rss 도메인 repository 함수 재사용성 향상, 테스트 코드 일관성, 최적화
  server/src/rss/dto/request/rss-management.dto.ts
  server/src/rss/dto/request/rss-register.dto.ts
  server/src/rss/dto/request/rss-reject.dto.ts
  server/src/rss/repository/rss.repository.ts
  server/src/rss/service/feed-crawler.service.ts
  server/src/rss/service/rss.service.ts
  server/test/rss/dto/rss-management.dto.spec.ts
  server/test/rss/e2e/accept.e2e-spec.ts
  server/test/rss/e2e/history/accept.e2e-spec.ts
  server/test/rss/e2e/history/reject.e2e-spec.ts
  server/test/rss/e2e/reject.e2e-spec.ts
  server/test/rss/e2e/rss.e2e-spec.ts
Labels: 🔨 Refactor, ✅ Test

#18 ♻️ refactor: statistic 도메인 repository 함수 재사용성 향상, 테스트 코드 일관성, 최적화
  server/src/statistic/dto/request/statistic-query.dto.ts
  server/test/statistic/dto/statistic-query.dto.spec.ts
  server/test/statistic/e2e/all.e2e-spec.ts
  server/test/statistic/e2e/platform.e2e-spec.ts
  server/test/statistic/e2e/today.e2e-spec.ts
Labels: 🔨 Refactor, ✅ Test

#12 ♻️ refactor: sonarQube에 나온 이슈 해결
  client/src/api/services/rss.ts
  client/src/components/RssRegistration/RssUrlInput.tsx
  client/src/components/admin/layout/AdminMember.tsx
  client/src/components/chart/PieChartItem.tsx
  client/src/components/chat/ChatButton.tsx
  client/src/components/chat/ChatItem.tsx
  client/src/components/chat/layout/ChatFooter.tsx
  client/src/components/chat/layout/ChatSection.tsx
  client/src/components/layout/Header.tsx
  client/src/components/layout/SideButton.tsx
  client/src/components/search/SearchButton.tsx
  client/src/components/search/SearchFilters/FilterButton.tsx
  client/src/components/search/SearchHigilight.tsx
  client/src/components/search/SearchResults/SearchResultList.tsx
  client/src/hooks/queries/useInfiniteScrollQuery.ts
  client/src/hooks/queries/useSearch.ts
  client/src/store/useChatStore.ts
Labels: 🔨 Refactor

#16 ✨ feat: 404페이지 추가
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/pages/NotFound.tsx
Labels: ✨ Feature

#19 📦 chore: feed-crawler 테스트를 위한 Jest 설치 및 경로 설정
  feed-crawler/.gitignore
  feed-crawler/package-lock.json
  feed-crawler/package.json
  feed-crawler/test/jest-e2e.json
  feed-crawler/test/jest-integration.json
  feed-crawler/test/jest-unit.json
Labels: 🔧 Chore

#20 ✅ test: Test환경에서 SQLite를 사용할 수 있도록 코드 추가 및 기존 코드 수정
  feed-crawler/package-lock.json
  feed-crawler/package.json
  feed-crawler/src/common/redis-access.ts
  feed-crawler/src/common/sqlite-access.ts
  feed-crawler/src/repository/feed.repository.ts
Labels: 🔧 Chore, ✅ Test

#21 ♻️ refactor: 채팅, 헤더 반응형 작업
  client/src/components/chat/ChatButton.tsx
  client/src/components/chat/layout/ChatFooter.tsx
  client/src/components/chat/layout/ChatSection.tsx
  client/src/components/layout/Header.tsx
  client/src/components/layout/Sidebar.tsx
  client/src/components/layout/navigation/DesktopNavigation.tsx
  client/src/components/layout/navigation/MobileNavigation.tsx
  client/src/components/search/SearchButton.tsx
  client/src/components/search/searchPages/SearchPages.tsx
  client/src/components/ui/pagination.tsx
  client/src/components/ui/sheet.tsx
  client/src/components/ui/sidebar.tsx
  client/src/hooks/common/useMediaQuery.ts
  client/src/store/useSidebarStore.ts
Labels: 🔨 Refactor

#25 📦 chore: github-actions yml 스크립트 변수명 수정
  .github/workflows/deploy_client.yml
  .github/workflows/deploy_server.yml
Labels: 🔧 Chore, 🔨 Refactor

#22 📦 chore: 테스트 환경 Testcontainer 적용
  package-lock.json
  server/configs/.env.db.test
  server/package-lock.json
  server/package.json
  server/src/app.module.ts
  server/src/common/database/load.config.ts
  server/src/common/test/test.module.ts
  server/src/common/test/test.service.ts
  server/test/config/mysql-container.ts
  server/test/config/typeorm-test-config.ts
  server/test/fixture/feed.fixture.ts
  server/test/jest-e2e.json
  server/test/jest-integration.json
  server/test/jest.setup.ts
  server/test/mysql-global-setup.ts
  server/test/mysql-global-teardown.ts
Labels: 🔧 Chore, ✅ Test

#23 ✅ test: RSS 등록 컴포넌트 테스트 코드 추가
  client/src/__tests__/__mocks__/components/common/RssRegistration.tsx
  client/src/__tests__/__mocks__/components/ui/Dialog.tsx
  client/src/__tests__/__mocks__/helpers/rssRegistrationMocks.ts
  client/src/__tests__/__mocks__/hooks/useRegisterRss.ts
  client/src/__tests__/components/common/Card/PostCardContent.test.tsx
  client/src/__tests__/components/common/RssRegistration/FormInput.test.tsx
  client/src/__tests__/components/common/RssRegistration/RssRegistrationModal.test.tsx
  client/src/__tests__/components/common/RssRegistration/RssValidation.test.ts
  client/src/__tests__/setup.tsx
  client/src/components/RssRegistration/FormInput.tsx
  client/src/components/RssRegistration/RssRegistrationModal.tsx
  client/src/components/RssRegistration/RssValidation.ts
  client/src/components/common/Alert.tsx
  client/src/components/layout/Header.tsx
Labels: ✅ Test

#27 ♻️ refactor: 반응형 레이아웃 변경, 모바일 카드 디자인 수정
  client/src/App.tsx
  client/src/components/common/Card/PostCard.tsx
  client/src/components/common/Card/PostCardContent.tsx
  client/src/components/common/Card/PostCardImage.tsx
  client/src/components/common/SectionHeader.tsx
  client/src/components/layout/Header.tsx
  client/src/components/layout/Layout.tsx
  client/src/components/sections/AnimatedPostGrid.tsx
  client/src/components/sections/LatestSection.tsx
  client/src/components/sections/MainContent.tsx
  client/src/components/sections/TrendingSection.tsx
  client/src/components/ui/card.tsx
  client/src/store/useMediaStore.ts
  client/src/types/card.ts
  client/src/types/post.ts
Labels: 🔨 Refactor

#30 🐛 fix: mock데이터에 blogPlatform 속성 추가
  client/src/__tests__/components/common/Card/PostCard.test.tsx
  client/src/__tests__/mocks/data/posts.ts
  client/src/api/mocks/data/posts.ts
  client/src/components/admin/login/AdminLoginModal.tsx
  client/src/constants/dummyData.ts
Labels: 👹 BugFix

#24 ✅ test: Feed-Crawler 테스트 설정 및 코드 추가
  .github/workflows/feed-crawler_test.yml
  feed-crawler/package-lock.json
  feed-crawler/package.json
  feed-crawler/src/common/constant.ts
  feed-crawler/src/common/logger.ts
  feed-crawler/src/common/mysql-access.ts
  feed-crawler/src/common/redis-access.ts
  feed-crawler/src/common/sqlite-access.ts
  feed-crawler/src/feed-crawler.ts
  feed-crawler/src/repository/feed.repository.ts
  feed-crawler/test/feed-crawling.e2e-spec.ts
  feed-crawler/test/jest-e2e.json
  feed-crawler/test/jest-integration.json
  feed-crawler/test/setup/jest.global-setup.ts
  feed-crawler/test/setup/testContext.setup.ts
  feed-crawler/test/setup/truncate-tables.setup.ts
Labels: 👹 BugFix, 🔧 Chore, ✅ Test

#26 ♻️ refactor: redis Testconatiners 적용
  server/package-lock.json
  server/package.json
  server/src/admin/service/admin.service.ts
  server/src/common/redis/redis.module.ts
  server/src/common/redis/redis.service.ts
  server/test/admin/e2e/logout.e2e-spec.ts
  server/test/integration-test-global-setup.ts
  server/test/integration-test-global-teardown.ts
  server/test/jest-e2e.json
  server/test/jest-integration.json
  server/test/jest.setup.ts
  server/test/mysql-global-setup.ts
  server/test/rss/e2e/history/accept.e2e-spec.ts
  server/test/rss/e2e/history/reject.e2e-spec.ts
Labels: 🔨 Refactor, ✅ Test

#32 ♻️ bugfix: 환경 변수 경로, DB 유지 보수 향상
  server/src/app.module.ts
  server/src/feed/entity/feed.entity.ts
Labels: 👹 BugFix
