Repository boostcampwm-2024/refactor-web05-Denamu, pull requests merged in 2025-02, with the labels that each got.

#35 📦 chore: Feed Crawler CI/CD 경로 분리 (1)
  .github/workflows/deploy_feed-crawler.yml
  .github/workflows/deploy_server.yml
  feed-crawler/package-lock.json
  feed-crawler/package.json
  feed-crawler/src/main.ts
Labels: 🔧 Chore

#44 ✨ feat: Tag-Map Entity 추가
  server/src/feed/entity/feed.entity.ts
  server/src/feed/entity/tag-map.entity.ts
  server/src/feed/module/feed.module.ts
  server/src/feed/repository/tag-map.repository.ts
Labels: ✨ Feature

#46 ✨ feat: RSS 승인시 피드 크롤링 AI를 활용하여 태그 + 요약 기능 추가
  .github/workflows/deploy_server.yml
  server/package-lock.json
  server/package.json
  server/src/feed/entity/feed.entity.ts
  server/src/feed/entity/tag-map.entity.ts
  server/src/rss/module/rss.module.ts
  server/src/rss/service/ai-tag-summary.service.ts
  server/src/rss/service/feed-crawler.service.ts
  server/src/rss/service/rss.service.ts
  server/test/rss/e2e/accept.e2e-spec.ts
Labels: ✨ Feature

#48 ✨ feat: 상세 모달 데이터 조회 API 구현, 페이지네이션에서 tag 정보를 반환하도록 수정
  server/src/feed/api-docs/readFeedDetail.api-docs.ts
  server/src/feed/api-docs/readFeedPagination.api-docs.ts
  server/src/feed/controller/feed.controller.ts
  server/src/feed/dto/request/feed-detail.dto.ts
  server/src/feed/dto/response/feed-detail.dto.ts
  server/src/feed/dto/response/feed-pagination.dto.ts
  server/src/feed/entity/feed.entity.ts
  server/src/feed/service/feed.service.ts
  server/test/feed/e2e/feed-detail.e2e-spec.ts
  server/test/fixture/feed.fixture.ts
  server/test/fixture/tag-map.fixture.ts
  server/test/integration-test-global-setup.ts
Labels: ✨ Feature, ✅ Test

#45 ✨ feat: Feature Feed-Crawler에서 클로드 API를 사용하도록 적용
  .github/workflows/deploy_feed-crawler.yml
  feed-crawler/package-lock.json
  feed-crawler/package.json
  feed-crawler/src/claude.service.ts
  feed-crawler/src/common/constant.ts
  feed-crawler/src/common/types.ts
  feed-crawler/src/container.ts
  feed-crawler/src/feed-crawler.ts
  feed-crawler/src/main.ts
  feed-crawler/src/repository/feed.repository.ts
  feed-crawler/src/repository/tag-map.repository.ts
  feed-crawler/src/types/dependency-symbols.ts
  feed-crawler/test/feed-crawling.e2e-spec.ts
  feed-crawler/test/setup/jest.global-setup.ts
  feed-crawler/test/setup/testContext.setup.ts
Labels: ✨ Feature, ✅ Test

#49 🐛 fix: 요약 글 제목 및 bold체로 출력되게 구현
  feed-crawler/src/common/constant.ts
  server/src/rss/service/ai-tag-summary.service.ts
Labels: 🧹 Cleanup

#53 🐛 fix: 실행 경로 수정
  ecosystem.config.js
  feed-crawler/package.json
Labels: 👹 BugFix

#54 🐛 fix: 테스트에서 포스트 카드 타입변경으로 인해 발생한 버그 수정
  client/src/__tests__/components/common/Card/PostCard.test.tsx
  client/src/__tests__/mocks/data/posts.ts
  client/src/components/common/Card/PostCardContent.tsx
Labels: 👹 BugFix

#55 🐛 fix: detail페이지에서 요악이 없을 경우 발생하는 에러 수정
  client/src/components/common/Card/detail/PostContent.tsx
  client/src/pages/PostDetailPage.tsx
Labels: 👹 BugFix

#47 ✨ feat: 로그인 및 회원가입 페이지 구현
  client/src/App.tsx
  client/src/components/auth/AuthBanner.tsx
  client/src/components/auth/AuthCard.tsx
  client/src/components/auth/AuthSignInForm.tsx
  client/src/components/auth/AuthSignUpForm.tsx
  client/src/components/auth/AuthSocialLoginButtons.tsx
  client/src/components/icons/social/GitHub.tsx
  client/src/components/icons/social/Google.tsx
  client/src/components/icons/social/Kakao.tsx
  client/src/components/icons/social/Naver.tsx
  client/src/components/layout/Header.tsx
  client/src/components/layout/Layout.tsx
  client/src/components/layout/Sidebar.tsx
  client/src/components/layout/SplitLayout.tsx
  client/src/components/layout/navigation/DesktopNavigation.tsx
  client/src/components/layout/navigation/MobileNavigation.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
Labels: ✨ Feature

#57 🐛 fix: denamu 아이콘 제대로 나오지 않는 현상
  client/src/components/auth/AuthBanner.tsx
  static/denamu-icon.svg
Labels: 👹 BugFix

#34 📦 chore: 프론트엔드 Docker 이미지 작성 개발 환경, 로컬 환경 Docker Compose (2)
  .gitignore
  client/.dockerignore
  client/.gitignore
  client/docker/Dockerfile.dev
  client/docker/Dockerfile.local
  client/vite.config.ts
  nginx/nginx.conf
  nginx/scripts/generate_cert.sh
Labels: 🔧 Chore, 🔨 Refactor

#39 📦 chore: 프론트 도커 환경변수 세팅 Docker Compose
  client/.env.dev
  client/.env.local
  client/.env.prod
  client/.gitignore
  client/package.json
  client/src/constants/endpoints.ts
  client/src/hooks/queries/useTrendingPosts.ts
Labels: 🔧 Chore

#60 📦 chore: Feed Crawler Prettier 설정
  feed-crawler/.prettierrc
  feed-crawler/src/claude.service.ts
  feed-crawler/src/common/constant.ts
  feed-crawler/src/common/logger.ts
  feed-crawler/src/common/mysql-access.ts
  feed-crawler/src/common/redis-access.ts
  feed-crawler/src/common/sqlite-access.ts
  feed-crawler/src/common/types.ts
  feed-crawler/src/container.ts
  feed-crawler/src/feed-crawler.ts
  feed-crawler/src/main.ts
  feed-crawler/src/repository/feed.repository.ts
  feed-crawler/src/repository/rss.repository.ts
  feed-crawler/src/repository/tag-map.repository.ts
  feed-crawler/src/types/database-connection.ts
  feed-crawler/src/types/dependency-symbols.ts
  feed-crawler/test/feed-crawling.e2e-spec.ts
  feed-crawler/test/setup/jest.global-setup.ts
  feed-crawler/test/setup/testContext.setup.ts
  feed-crawler/test/setup/truncate-tables.setup.ts
Labels: 🔧 Chore

#56 ♻️ refactor: AI Rate Limit을 해결하기 위한 Server 코드 변경
  server/src/common/redis/redis.constant.ts
  server/src/rss/module/rss.module.ts
  server/src/rss/service/ai-tag-summary.service.ts
  server/src/rss/service/feed-crawler.service.ts
  server/src/rss/service/rss.service.ts
  server/test/rss/e2e/accept.e2e-spec.ts
Labels: 🔨 Refactor

#36 📦 chore: Feed Crawler Docker 이미지 작성 개발 환경, 로컬 환경 Docker Compose (3)
  feed-crawler/.dockerignore
  feed-crawler/docker/Dockerfile.dev
  feed-crawler/docker/Dockerfile.local
Labels: 🔧 Chore, 🔨 Refactor

#37 📦 chore: Server Docker 이미지 작성 개발 환경, 로컬 환경 Docker Compose (4)
  server/.dockerignore
  server/docker/Dockerfile.dev
  server/docker/Dockerfile.local
Labels: 🔧 Chore, 🔨 Refactor

#62 🐛 fix: 배포 스크립트 배포 로직 변경
  .github/workflows/deploy_client.yml
  .github/workflows/deploy_feed-crawler.yml
  .github/workflows/deploy_server.yml
Labels: 👹 BugFix, ✨ Feature

#63 🐛 fix: yaml script 내에 주석 제거
  .github/workflows/deploy_feed-crawler.yml
  .github/workflows/deploy_server.yml
Labels: 👹 BugFix

#64 📦 chore: jest timeout docker 시간 설정
  feed-crawler/test/jest-e2e.json
  feed-crawler/test/jest-integration.json
  feed-crawler/test/jest-unit.json
  server/test/jest-e2e.json
  server/test/jest-integration.json
  server/test/jest-unit.json
Labels: 🔧 Chore

#65 ✨ feat: 공유하기 기능 추가 및 리팩토링
  client/index.html
  client/src/components/common/Card/PostCard.tsx
  client/src/components/common/Card/PostDetail.tsx
  client/src/components/common/Card/detail/LikeButton.tsx
  client/src/components/common/Card/detail/PostContent.tsx
  client/src/components/common/Card/detail/ShareButton.tsx
  client/src/components/ui/toast.tsx
  client/src/constants/messages.ts
  client/src/hooks/common/usePostCardActions.ts
  client/src/pages/PostDetailPage.tsx
Labels: ✨ Feature

#66 🐛 fix: 조회수 증가 로직변경으로 인한 테스트 수정
  client/src/__tests__/components/common/Card/PostCard.test.tsx
Labels: 👹 BugFix

#67 🐛 fix: 링크복사 url 버그 수정
  client/src/components/common/Card/detail/ShareButton.tsx
Labels: 👹 BugFix

#61 ♻️ refactor: AI Rate Limit 해결, AI 응답 예외 처리를 위한 AI Queue 사용 및 Cron Task 추가
  feed-crawler/src/claude.service.ts
  feed-crawler/src/common/constant.ts
  feed-crawler/src/common/redis-access.ts
  feed-crawler/src/common/types.ts
  feed-crawler/src/feed-crawler.ts
  feed-crawler/src/main.ts
  feed-crawler/src/repository/feed.repository.ts
  server/src/feed/api-docs/readRecentFeedList.api-docs.ts
  server/src/feed/api-docs/readTrendFeedList.api-docs.ts
  server/src/feed/dto/response/recent.dto.ts
  server/src/feed/service/feed.service.ts
Labels: 🔨 Refactor

#69 [긴급] 🐛 fix: CI/CD 버그 수정 및 사용되지 않는 환경 변수 제거
  .github/workflows/deploy_feed-crawler.yml
  .github/workflows/deploy_server.yml
  feed-crawler/src/common/mysql-access.ts
Labels: 👹 BugFix, 🔧 Chore

#68 ✨ feat: 프로필(/profile) 페이지 구현
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/profile/common/Section.tsx
  client/src/components/profile/header/Header.tsx
  client/src/components/profile/header/index.ts
  client/src/components/profile/header/ui/ActivityGraph/ActivityGraph.tsx
  client/src/components/profile/header/ui/ActivityGraph/DayCell.tsx
  client/src/components/profile/header/ui/ActivityGraph/DayLabels.tsx
  client/src/components/profile/header/ui/ActivityGraph/Legend.tsx
  client/src/components/profile/header/ui/ActivityGraph/MonthLabels.tsx
  client/src/components/profile/header/ui/ActivityGraph/Week.tsx
  client/src/components/profile/header/ui/Avatar.tsx
  client/src/components/profile/header/ui/Banner.tsx
  client/src/components/profile/header/ui/Info.tsx
  client/src/components/profile/header/ui/Stats.tsx
  client/src/components/profile/sections/LikedPosts.tsx
  client/src/components/profile/sections/RecentPosts.tsx
  client/src/components/profile/sections/Settings.tsx
  client/src/components/profile/sidebar/Item.tsx
  client/src/components/profile/sidebar/Sidebar.tsx
  client/src/constants/profile.ts
  client/src/pages/Profile.tsx
  client/src/types/activity.ts
  client/src/types/profile.ts
  client/src/utils/.gitkeep
  client/src/utils/activity.ts
  client/src/utils/color.ts
  client/src/utils/date.ts
Labels: ✨ Feature
